### ISSUE TITLE
Link(s) missing

### ISSUE THREAD

**Issue by anjohnson** [qtepics/qeframework#2]
Hi,

Can I suggest that your README.md file(s) should contain a link to https://qtepics.github.io/index.html which will allow potential users to see your website properly rendered without having to know how to get there from the repo?

BTW I just changed the link on the EPICS Extensions web-pages to point to that githubio page, hope that's OK.

- Andrew J

**Comment by andrewstarritt** [comment]
Hi Andrew, 
Good idea, will do that.

**Comment by pozara** [comment]
Link's have been added. I'll close this issue.
